sample_rate: 32000
image_size: 224
train_csv: train.csv
# train_audio_dir: train_resampled_with_nocall
train_audio_dir: train_resampled_with_nocall_npy
learning_rate: 1e-3
epoch: 50
threshold: 0.5
mixup: false
debug: false
multi: true
gpu: true

dataloader:
  num_workers: 64
  batch_size: 128
  pin_memory: true

composer:
  wave_transform:
    - name: TimeShifting
      param:
        p: 0.5
    - name: SpeedTuning
      param:
        p: 0.5
    - name: AddGaussianNoise
      param:
        p: 0.5
    - name: PitchShift
      param:
        p: 0.5
        n_steps: 4
    - name: Gain
      param:
        p: 0.5
    - name: PolarityInversion
      param:
        p: 0.5
    - name: StretchAudio
      param:
        p: 0.5
  melspectrogram_parameters:
    n_mels: 128
    fmin: 20
    fmax: 16000
model:
  name: efficientnet_b4
  pretrained: true
  in_chans: 1

hydra:
  run:
    # dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: ./outputs/debug${debug}-${now:%Y%m%d%H%M%S}
